const NOTE_TIME = 10;
const TURN_TIME_STANDARD = 90;
const TURN_TIME_RELAXED = 150;
const FEEDBACK_TIME = 5;
const ROUND_NUMBER = 2;

export {
  NOTE_TIME,
  TURN_TIME_STANDARD,
  TURN_TIME_RELAXED,
  FEEDBACK_TIME,
  ROUND_NUMBER,
};
